"""Render a role tree into the surface Codex reads.

Codex reads a single AGENTS.md and configures MCP servers in TOML. It has no
per-skill artifact and no nested-role concept, so this adapter flattens the
tree into one document — and says so, because a flattened surface loses the
disclosure the model was built to provide.
"""

from __future__ import annotations

from typing import ClassVar, Iterable

from ..core.registry import RoleRegistry
from ..core.role import Role
from ..core.servers import HTTPConnection, MCPServer, StdioConnection
from .base import (
    Artifact,
    TargetAdapter,
    TargetCapabilities,
    collect_servers,
    iter_roles,
)
from .markdown import heading, render_capability_table, render_role_routes


class CodexAdapter(TargetAdapter):
    """Emit AGENTS.md and a Codex MCP configuration fragment."""

    name: ClassVar[str] = "codex"
    display_name: ClassVar[str] = "Codex"
    capabilities: ClassVar[TargetCapabilities] = TargetCapabilities(
        separate_skill_files=False,
        mcp_configuration=True,
        tool_allowlist=False,
        progressive_disclosure=False,
        nested_roles=False,
    )

    agents_path: ClassVar[str] = "AGENTS.md"
    config_path: ClassVar[str] = ".codex/config.toml"

    def _render_artifacts(
        self,
        role: Role,
        registry: RoleRegistry,
    ) -> Iterable[Artifact]:
        yield Artifact(path=self.agents_path, content=self._agents(role))

        servers = [
            server
            for server in collect_servers(role)
            if server.connection is not None
        ]
        if servers:
            yield Artifact(
                path=self.config_path,
                content=self._config(servers),
                media_type="application/toml",
            )

    def _agents(self, role: Role) -> str:
        lines = [
            heading(1, role.name),
            "",
            role.description,
            "",
            role.instructions.strip(),
            "",
        ]

        root_table = render_capability_table(role, include_children=False)
        if root_table:
            lines += root_table + [""]

        if role.children:
            lines += [
                heading(2, "Areas of responsibility"),
                "",
                *render_role_routes(role.children),
                "",
            ]

        for node in iter_roles(role):
            if node is role:
                continue
            lines += [heading(2, node.name), "", node.description, ""]
            lines += [node.instructions.strip(), ""]
            for skill in node.skills:
                lines += [
                    heading(3, f"Skill: {skill.name}"),
                    "",
                    skill.description,
                    "",
                    skill.instructions.strip(),
                    "",
                ]
            table = render_capability_table(node, include_children=False)
            if table:
                lines += table + [""]

        for skill in role.skills:
            lines += [
                heading(2, f"Skill: {skill.name}"),
                "",
                skill.description,
                "",
                skill.instructions.strip(),
                "",
            ]

        return "\n".join(lines).rstrip() + "\n"

    def _config(self, servers: list[MCPServer]) -> str:
        blocks: list[str] = [
            "# Generated by Contexture. Merge into ~/.codex/config.toml.",
            "",
        ]
        for server in servers:
            connection = server.connection
            blocks.append(f"[mcp_servers.{server.server_id}]")
            if isinstance(connection, StdioConnection):
                blocks.append(f"command = {_toml_str(connection.command)}")
                if connection.args:
                    rendered = ", ".join(_toml_str(arg) for arg in connection.args)
                    blocks.append(f"args = [{rendered}]")
                if connection.env:
                    blocks.append("")
                    blocks.append(f"[mcp_servers.{server.server_id}.env]")
                    for key in sorted(connection.env):
                        blocks.append(f"{key} = {_toml_str(connection.env[key])}")
            elif isinstance(connection, HTTPConnection):
                blocks.append(f"url = {_toml_str(connection.url)}")
                if connection.headers:
                    blocks.append("")
                    blocks.append(f"[mcp_servers.{server.server_id}.http_headers]")
                    for key in sorted(connection.headers):
                        blocks.append(f"{key} = {_toml_str(connection.headers[key])}")
            blocks.append("")
        return "\n".join(blocks).rstrip() + "\n"

    def _render_notes(
        self,
        role: Role,
        registry: RoleRegistry,
    ) -> Iterable[str]:
        yield (
            "The Codex MCP configuration is user-level, not project-level; "
            f"{self.config_path} is a fragment to merge into "
            "~/.codex/config.toml rather than a file Codex reads in place."
        )


def _toml_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
